from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


FONT_WIDTH = 8
FONT_HEIGHT = 16
FONT_FIRST_CHAR = 0x20
FONT_LAST_CHAR = 0x7E
CHARS = "".join(chr(code) for code in range(FONT_FIRST_CHAR, FONT_LAST_CHAR + 1))

PROJECT_ROOT = Path(r"d:\Projects\BanJiuOS")
OUTPUT_FILE = PROJECT_ROOT / r"kernel\src\core\font.c"

FONT_CANDIDATES = [
    Path(r"C:\Windows\Fonts\CascadiaMono.ttf"),
    Path(r"C:\Windows\Fonts\consola.ttf"),
    Path(r"C:\Windows\Fonts\cour.ttf"),
]


def c_char_literal(ch: str) -> str:
    if ch == "\\":
        return "\\\\"
    if ch == "'":
        return "\\'"
    return ch


def glyph_bbox(font: ImageFont.FreeTypeFont, ch: str) -> tuple[int, int, int, int]:
    dummy = Image.new("L", (FONT_WIDTH, FONT_HEIGHT), 0)
    draw = ImageDraw.Draw(dummy)
    bbox = draw.textbbox((0, 0), ch, font=font)
    if bbox is None:
        return (0, 0, 0, 0)
    return bbox


def font_fits(font: ImageFont.FreeTypeFont) -> bool:
    for ch in CHARS:
        left, top, right, bottom = glyph_bbox(font, ch)
        if (right - left) > FONT_WIDTH or (bottom - top) > FONT_HEIGHT:
            return False
    return True


def load_font() -> tuple[ImageFont.FreeTypeFont, Path, int]:
    for font_path in FONT_CANDIDATES:
        if not font_path.exists():
            continue
        for size in range(FONT_HEIGHT, 7, -1):
            font = ImageFont.truetype(str(font_path), size=size)
            if font_fits(font):
                return font, font_path, size
    raise RuntimeError("No suitable TrueType font found")


def render_char(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    image = Image.new("1", (FONT_WIDTH, FONT_HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    draw.fontmode = "1"
    left, top, right, bottom = glyph_bbox(font, ch)
    glyph_width = right - left
    glyph_height = bottom - top
    x = (FONT_WIDTH - glyph_width) // 2 - left
    y = (FONT_HEIGHT - glyph_height) // 2 - top
    draw.text((x, y), ch, font=font, fill=255)

    rows = []
    for y in range(FONT_HEIGHT):
        bits = 0
        for x in range(FONT_WIDTH):
            if image.getpixel((x, y)):
                bits |= 1 << (FONT_WIDTH - 1 - x)
        rows.append(bits)
    return rows


def build_font_source() -> str:
    font, font_path, font_size = load_font()
    lines = [
        "#include <font.h>",
        "#include <framebuffer.h>",
        "",
        f"// Auto-generated by generate_font.py from {font_path.name} size {font_size}",
        "const u8 font_bitmap[FONT_CHAR_COUNT][FONT_HEIGHT] = {",
    ]

    for ch in CHARS:
        rows = render_char(font, ch)
        row_text = ", ".join(f"0x{row:02X}" for row in rows)
        lines.append(f"    {{ {row_text} }}, // '{c_char_literal(ch)}'")

    lines.extend(
        [
            "};",
            "",
            "void font_init(void) {",
            "}",
            "",
            "void font_draw_char(u8 c, u16 x, u16 y, u32 fg_color, u32 bg_color) {",
            "    if (c < FONT_FIRST_CHAR || c > FONT_LAST_CHAR) {",
            "        c = '?';",
            "    }",
            "",
            "    u32 char_idx = c - FONT_FIRST_CHAR;",
            "",
            "    for (u8 row = 0; row < FONT_HEIGHT; row++) {",
            "        u8 bits = font_bitmap[char_idx][row];",
            "",
            "        for (u8 col = 0; col < FONT_WIDTH; col++) {",
            "            u32 px = x + col;",
            "            u32 py = y + row;",
            "",
            "            if (bits & (0x80 >> col)) {",
            "                framebuffer_draw_pixel(px, py, fg_color);",
            "            } else {",
            "                framebuffer_draw_pixel(px, py, bg_color);",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "void font_print(const char* str, u16 x, u16 y, u32 fg_color, u32 bg_color) {",
            "    u16 cx = x;",
            "    u16 cy = y;",
            "",
            "    while (*str) {",
            "        if (*str == '\\n') {",
            "            cx = x;",
            "            cy += FONT_HEIGHT;",
            "            str++;",
            "            continue;",
            "        }",
            "",
            "        if (*str == '\\r') {",
            "            cx = x;",
            "            str++;",
            "            continue;",
            "        }",
            "",
            "        font_draw_char((u8)*str, cx, cy, fg_color, bg_color);",
            "        cx += FONT_WIDTH;",
            "",
            "        if (cx + FONT_WIDTH > g_framebuffer.width) {",
            "            cx = x;",
            "            cy += FONT_HEIGHT;",
            "        }",
            "",
            "        str++;",
            "    }",
            "}",
            "",
            "void font_clear_screen(u32 color) {",
            "    framebuffer_clear(color);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    source = build_font_source()
    OUTPUT_FILE.write_text(source, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
